# Configurações do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Alissonkiss@12
spring.datasource.driver-class-name=org.postgresql.Driver
senha admin=alissonAl23@3312AA

# Configuração do Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# JWT
jwt.secret=6b8f7e2c9d4a1f3e5c7b0a2d8e4f6c1b
jwt.expiration=86400000